"""empty message

Revision ID: 08d2ce120771
Revises: b186f42cbb9e
Create Date: 2024-02-04 18:39:27.397535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08d2ce120771'
down_revision = 'b186f42cbb9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint('quiz_ibfk_1', type_='foreignkey')
        batch_op.drop_column('module_id')

    with op.batch_alter_table('user_quiz_take', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.String(length=16), nullable=False))
        batch_op.drop_constraint('user_quiz_take_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['id'])
        batch_op.drop_column('module_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quiz_take', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', mysql.VARCHAR(length=16), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_quiz_take_ibfk_2', 'module', ['module_id'], ['id'])
        batch_op.drop_column('quiz_id')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', mysql.VARCHAR(length=16), nullable=False))
        batch_op.create_foreign_key('quiz_ibfk_1', 'module', ['module_id'], ['id'])

    # ### end Alembic commands ###
