"""empty message

Revision ID: 385597d657ee
Revises: e0a4fac49971
Create Date: 2024-02-05 13:50:37.083930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '385597d657ee'
down_revision = 'e0a4fac49971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('cognito_id')
        batch_op.drop_column('cognito_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cognito_id', mysql.VARCHAR(length=36), nullable=False))
        batch_op.create_index('cognito_id', ['cognito_id'], unique=False)

    # ### end Alembic commands ###
