"""empty message

Revision ID: 47e8e12ea44c
Revises: c99de6824d15
Create Date: 2024-02-14 17:04:35.618392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47e8e12ea44c'
down_revision = 'c99de6824d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_index('name')

    with op.batch_alter_table('user_module', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('module_id',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('points',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_module', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('module_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    # ### end Alembic commands ###
