"""changed size of ids to 36 not 16

Revision ID: 6edca1db5898
Revises: f6270e61f6aa
Create Date: 2024-03-04 17:40:26.894201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6edca1db5898'
down_revision = 'f6270e61f6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('lesson_id',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.alter_column('module_id',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_index('name')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('module_id',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('user_quiz_take', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('quiz_id',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_quiz_take', schema=None) as batch_op:
        batch_op.alter_column('quiz_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('module_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)
        batch_op.alter_column('module_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('lesson_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
