"""empty message

Revision ID: 904a6828fb7e
Revises: 385597d657ee
Create Date: 2024-02-07 16:40:25.969230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904a6828fb7e'
down_revision = '385597d657ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cognito_username', sa.String(length=36), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cognito_username')

    # ### end Alembic commands ###
