"""thrid test migration

Revision ID: a81d969a1cdb
Revises: f2d9687e3b99
Create Date: 2023-12-14 18:09:31.728391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a81d969a1cdb'
down_revision = 'f2d9687e3b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('remail')
        batch_op.drop_column('remail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remail', mysql.VARCHAR(length=120), nullable=False))
        batch_op.create_index('remail', ['remail'], unique=False)

    # ### end Alembic commands ###
