"""foreign key added

Revision ID: b186f42cbb9e
Revises: bf8621d7cb05
Create Date: 2024-02-04 18:02:30.563955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b186f42cbb9e'
down_revision = 'bf8621d7cb05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.String(length=16), nullable=False))
        batch_op.create_foreign_key(None, 'module', ['module_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('module_id')

    # ### end Alembic commands ###
