"""empty message

Revision ID: c99de6824d15
Revises: 904a6828fb7e
Create Date: 2024-02-07 20:41:30.021668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99de6824d15'
down_revision = '904a6828fb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('name')
        batch_op.drop_index('nickname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('nickname', ['nickname'], unique=False)
        batch_op.create_index('name', ['name'], unique=False)
        batch_op.create_index('email', ['email'], unique=False)

    # ### end Alembic commands ###
