"""empty message

Revision ID: cbc81c3b093c
Revises: a81d969a1cdb
Create Date: 2024-02-02 11:25:19.528392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc81c3b093c'
down_revision = 'a81d969a1cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('imageId', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('imageId')
        batch_op.drop_column('teacher')

    # ### end Alembic commands ###
