"""empty message

Revision ID: e0a4fac49971
Revises: 08d2ce120771
Create Date: 2024-02-04 18:55:39.588420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0a4fac49971'
down_revision = '08d2ce120771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.String(length=16), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'module', ['module_id'], ['id'])

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.String(length=16), nullable=False))
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'module', ['module_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.drop_column('module_id')

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.drop_column('module_id')

    # ### end Alembic commands ###
