"""updated user class to match cognito

Revision ID: f4f955067bbd
Revises: a4ff699a7de1
Create Date: 2024-02-04 17:43:37.547218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4f955067bbd'
down_revision = 'a4ff699a7de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('nickname', sa.String(length=120), nullable=False))
        batch_op.drop_index('username')
        batch_op.create_unique_constraint(None, ['nickname'])
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('username', ['username'], unique=False)
        batch_op.drop_column('nickname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
