"""add documents

Revision ID: f6270e61f6aa
Revises: 5254c7348dba
Create Date: 2024-03-04 17:33:32.719281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6270e61f6aa'
down_revision = '5254c7348dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('s3_url', sa.Text(), nullable=False),
    sa.Column('s3_url_expiry', sa.DateTime(), nullable=False),
    sa.Column('lesson_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
