import os
from dotenv import load_dotenv
load_dotenv()

DB_HOSTNAME = os.getenv("DB_HOSTNAME")
DB_PORT = os.getenv("DB_PORT")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_NAME = os.getenv("DB_NAME")
DB_USERNAME = os.getenv("DB_USERNAME")

COGNITO_REGION = os.getenv("COGNITO_REGION")
COGNITO_USERPOOL_ID = os.getenv("COGNITO_USERPOOL_ID")
COGNITO_JWT_HEADER_NAME = os.getenv("COGNITO_JWT_HEADER_NAME")
COGNITO_JWT_HEADER_PREFIX = os.getenv("COGNITO_JWT_HEADER_PREFIX")
COGNITO_APP_CLIENT_ID = os.getenv("COGNITO_APP_CLIENT_ID")
COGNITO_CHECK_TOKEN_EXPIRATION = os.getenv("COGNITO_CHECK_TOKEN_EXPIRATION")
CORS_HEADERS = 'Content-Type'

# Correct the driver name to 'pymysql'
SQLALCHEMY_DATABASE_URI = f"mysql+pymysql://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOSTNAME}:{DB_PORT}/{DB_NAME}"
